### ISSUE TITLE
 TypeError: Cannot read property 'isJoi' of null

### ISSUE THREAD

**Issue by iraycd** [roboncode/orango#61]
```bash
(node:36) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isJoi' of null
    at RequiredKeys.parse (/app/node_modules/tangjs/lib/helpers/getRequiredPaths.js:43:15)
    at RequiredKeys.parse (/app/node_modules/tangjs/lib/helpers/getRequiredPaths.js:64:26)
    at RequiredKeys.parse (/app/node_modules/tangjs/lib/helpers/getRequiredPaths.js:64:26)
    at RequiredKeys.parse (/app/node_modules/tangjs/lib/helpers/getRequiredPaths.js:64:26)
    at RequiredKeys.parse (/app/node_modules/tangjs/lib/helpers/getRequiredPaths.js:64:26)
    at RequiredKeys.parse (/app/node_modules/tangjs/lib/helpers/getRequiredPaths.js:64:26)
    at new RequiredKeys (/app/node_modules/tangjs/lib/helpers/getRequiredPaths.js:39:12)
    at module.exports (/app/node_modules/tangjs/lib/helpers/getRequiredPaths.js:85:12)
    at new Schema (/app/node_modules/tangjs/lib/Schema.js:17:26)
    at new Model (/app/node_modules/tangjs/lib/Model.js:17:16)
```

**Version**: 1.0.0-alpha-2.0.14

**Code**
```javascript
module.exports = ({ orango }) => {
  const { OPERATIONS } = orango.consts
  const schema = new orango.Schema(
    {
      name: String,
      location: [Number, Number],
      created: Date
      updated: Date
    },
    {
      indexes: [
        { type: 'geo', fields: ['location'] }
      ]
    }
  )

  const Site = orango.model('Site', schema)

  Site.on(OPERATIONS.INSERT, async model => {
    model.created = Date.now()
  })

  Site.on(OPERATIONS.UPDATE, async model => {
    model.updated = Date.now()
  })

  return Site
}

```

**Comment by roboncode** [comment]
Fixed in release v1.0.0-alpha-2.1
