### ISSUE TITLE
findOne is not a function, and not returning a FALSE when no records found

### ISSUE THREAD

**Issue by armenr** [roboncode/orango#71]
Hey there - am I mistaken to believe that there's a "findOne" method on Models?

It's used as an example in the docs, but doesn't appear to actually work or exist (checked the master branch of the codebase too).

stuff.js:
```
let query = await User.findOne({ username: username, password: password })
        // .where({ username, password })
        .return(orango.return.one());

      let queryData = JSON.stringify(query);
      console.log(queryData.green);

      let aql = await query.toAQL(true);
      console.log(aql.cyan);

      let rawData = await query.exec();
      console.log('rawData'.green, rawData);

```

And in the logs:
```
There was a booboo in User.findByUnamePass TypeError: User.findOne is not a function
    at Function.projectUserModel.User.findByUnamePass (/Users/armenr/Desktop/project-new/projectzer0/packages/project-api/src/models/projectGenerics/projectUser.js:49:30)
    at router.post (/Users/armenr/Desktop/project-new/projectzer0/packages/project-api/src/routers/authRouter.js:51:35)
    at Layer.handle [as handle_request] (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/layer.js:95:5)
    at /Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:317:13)
    at /Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/armenr/Desktop/project-new/projectzer0/node_modules/express/lib/router/index.js:275:10)
```

An additional question: If we make a query call, and it returns nothing, how can we check that?

I have awaits that return undefined, rather than return something like "There was no user found."

How do I address that?

Thanks again!

**Comment by armenr** [comment]
Additionally, this query doesn't appear to be valid either? 

```let query = await User.find({ username: username, password: password });```

I get: `There was a booboo in User.findByUnamePass TypeError: query.toAQL is not a function`

**Comment by armenr** [comment]
Additional question:

Is there a difference between 
```
let query = User.find({ username: username, password: password })
        .limit(1)
```

and 
```      
let query = User.find({ username: username, password: password })
        .limit(1)
        // .where({ username, password })
        .return(orango.return.one());
```

**Comment by armenr** [comment]
And finally, I have a question about errors, throwing errors, and detecting/logging/surfacing mistakes:

My colleague had coded this up:
```
  User.findByUnamePass = async (username, pass) => {
    const hash = crypto.createHash('sha256');
    const password = hash.update(pass).digest('hex');
    const user = await User.find()
      .one()
      .where({ username, password });
    return user;
  };
};

```

All the while, it was being called, it never once let us know that the query might be malformed, that the AQL fails, or that it's returning undefined. 

In general, how do we handle this? What's the convention with Orango? :) I'm happy to help brainstorm. Not trying to be bitchy or ungrateful.

**Comment by roboncode** [comment]
Good questions, I will try to answer them the best I can. 

1) findOne() should not be listed in the docs, that was the old way. the appropriate way is to do.

```javascript 
async User.find().one().where(filtersHere...)
```

I will need to update the docs correct that.

2) diff between using return({one:true}) will return the result as an object or null. Without that it will return the results as an array[].

3) If you are finding a place where you know an error is begin produced and it not returned or thrown, let me know and I will look into it. 

Let me know if you have more questions, feedback is welcome! Rob

**Comment by roboncode** [comment]
Closing due to no activity.
