### ISSUE TITLE
TypeError: joi.requiredKeys is not a function

### ISSUE THREAD

**Issue by altras** [roboncode/orango#78]
Hello!

I have the following schema:

```
const schema = new db.Schema(
    {
      name: { type: String, required: true },
      cb_uuid: { type: String, required: true },
      permalink: { type: String, required: true },
      cb_url: String,
      type: String,
      rank: String,
      created_at: String,
      updated_at: String,
      legal_name: String,
      roles: String,
      domain: String,
      homepage_url: String,
      country_code: String,
      state_code: String,
      region: String,
      city: String,
      address: String,
      postal_code: String,
      status: String,
      short_description: String,
      category_list: String,
      category_groups_list: String,
      num_funding_rounds: String,
      total_funding_usd: String,
      total_funding: String,
      total_funding_currency_code: String,
      founded_on: String,
      last_funding_on: String,
      closed_on: String,
      employee_count: String,
      email: String,
      phone: String,
      facebook_url: String,
      linkedin_url: String,
      twitter_url: String,
      logo_url: String,
      alias1: String,
      alias2: String,
      alias3: String,
      primary_role: String,
      num_exits: String,
      // scenic proprietary data
      scenicRank: Number,
      demandForLiquidity: Number,
      desirability: Number,
      marketability: Number,
      sentiment: Number,
    },
    {
      indexes: [
        {
          type: db.consts.SCHEMA.INDEX.FULLTEXT,
          fields: ['name'],
        },
      ],
    },
  )
```

and I want to do 

```
      const org = await Organization.find()
        .one()
        .where({ cb_uuid: data.uuid })
        .return(db.return.one().model())
      if (_.isUndefined(org)) return `${data.uuid} is not found`
      org.scenicRank = Number(data['Overall Rank'])
      org.demandForLiquidity = Number(data['Demand for Liquidity'])
      org.desirability = Number(data['Desirability'])
      org.marketability = Number(data['Marketability'])
      org.sentiment = Number(data['Sentiment'])
      return await org.save()
```

but I receive

```
(node:12512) UnhandledPromiseRejectionWarning: TypeError: joi.requiredKeys is not a function
    at Schema.validate (/Users/altras/dev/scenic-amp/cells/api/node_modules/tangjs/lib/Schema.js:71:19)
    at Schema.validate (/Users/altras/dev/scenic-amp/cells/api/node_modules/orango/lib/Schema.js:111:28)
    at Organization.validate (/Users/altras/dev/scenic-amp/cells/api/node_modules/tangjs/lib/Model.js:92:33)
    at Organization.toObject (/Users/altras/dev/scenic-amp/cells/api/node_modules/tangjs/lib/Model.js:115:25)
    at Builder.<anonymous> (/Users/altras/dev/scenic-amp/cells/api/node_modules/tangjs/lib/builder.js:18:22)
    at asyncForEach (/Users/altras/dev/scenic-amp/cells/api/node_modules/tangjs/lib/builder.js:64:39)
    at <anonymous>
(node:12512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:12512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

which is very odd because I don't use Joi at all 🤔 Any points how to fix this are welcomed :bow:

**Comment by roboncode** [comment]
Orango uses Joi for the validation. You are using a reserved word `type` in your schema. If you would like to use this word, you need to change it to `type: {type: String},`
